name: wilguerrero
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54666
title: Wil Guerrero Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#808080'
    - '#535353'
    - '#c1c1c1'
    - '#e5e5e5'
  brandStrength: 0.8125
  lightness: 0.021613561548292637
  saturation: 0.9312366812955588
  rhythmicContrast: 0.5
purpose: []
