name: wilguerrero
favicon: null
layout_spectrum: 1
typography_spectrum: 0.56111
title: Wil Guerrero Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#830000'
    - '#905900'
    - '#fefefd'
    - '#c78d44'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
