name: wilguerrero
favicon: null
layout_spectrum: 0.57496
typography_spectrum: 0.88621
title: Wil Guerrero Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#830000'
    - '#905900'
    - '#fefefd'
    - '#c78d44'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
