name: wilguerrero
favicon: null
layout_spectrum: 0.88079
typography_spectrum: 0.45876
title: Wil Guerrero Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0d0d0d'
    - '#808080'
    - '#535353'
    - '#c1c1c1'
    - '#e5e5e5'
  brandStrength: 0.8125
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 1
purpose: []
