name: wilguerrero
favicon: null
layout_spectrum: 0.57496
typography_spectrum: 0.90909
title: Wil Guerrero Photography
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c1c1c'
    - '#d1d1d1'
    - '#3d3d3d'
    - '#555555'
    - '#a0a0a0'
  brandStrength: 0
  lightness: 0.5625
  saturation: 1
  rhythmicContrast: 0
purpose: []
